language: java
jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "TvNqVycehzj4uLzHnvsNEAyf3KA0JIiTOO36J0NAN6ECPe2vdmswDdaxxbjeRmh6Oe9i1KCebRwps9RjKEoYqUUIgRzgaDL3qp/Hc09rVVS43uVFLLfJ1auRzTVfUccPA7W9HmciyxEs/9niANybCl++Ds20XX8Wmgy2PXvCIt0="

addons:
  coverity_scan:
    project:
      name: "TimePath/jqcc"
      description: "Build submitted via Travis CI"
    notification_email: andrew.hardaker1995@gmail.com
    build_command_prepend: "gradle clean"
    build_command:   "gradle build"
    branch_pattern: coverity_scan

after_script:
 - ./gradlew jacocoRootReport coveralls
